// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Apr 30 19:20:48 2010
#ifndef DBADMIN_H
#define DBADMIN_H

#include <wx/wx.h>
#include <wx/image.h>
#include "../common/DBOperator.h"

// mysql admin: KTVAdmin passwd:admin

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class DBAdmin: public wxFrame, public DBOperator {
public:
    // begin wxGlade: DBAdmin::ids
    // end wxGlade

    DBAdmin(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

    void InitMenus();

    void OnSearch(wxCommandEvent& event);
    void OnDelete(wxCommandEvent& event);
    void OnNew(wxCommandEvent& event);
    void OnSave(wxCommandEvent& event);

    void OnAbout(wxCommandEvent& WXUNUSED(event));
    void OnExit(wxCommandEvent& WXUNUSED(event));
private:
    // begin wxGlade: DBAdmin::methods
    void set_properties();
    void do_layout();
    // end wxGlade

    void InitDatabase();
    enum
    {
        NONE,
        NEW,
        NOT_MODIFIED,
        MODIFIED,
    } m_state;
protected:
    // begin wxGlade: DBAdmin::attributes
    wxStaticText* label_1;
    wxTextCtrl* text_ctrl_search;
    wxButton* button_search;
    wxStaticText* label_SongName;
    wxTextCtrl* text_SongName;
    wxStaticText* label_Singer;
    wxTextCtrl* text_Singer;
    wxStaticText* label_Country;
    wxTextCtrl* text_Country;
    wxStaticText* label_Sex;
    wxComboBox* combo_box_Sex;
    wxStaticText* label_Band;
    wxTextCtrl* text_ctrl_Band;
    wxStaticText* label_Language;
    wxComboBox* combo_box_Language;

    wxButton *button_new, *button_delete, *button_save;

    wxStatusBar* status_bar;

    wxPanel* panel_search, *panel_detail;
    // end wxGlade

    DECLARE_EVENT_TABLE()
}; // wxGlade: end class

enum ID_COMMAND
{
    ID_SEARCH,
    ID_NEW,
    ID_DELETE,
    ID_SAVE,

    ID_FILE_EXIT,
    ID_HELP_ABOUT,
};

#endif // DBADMIN_H
