// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Apr 30 19:20:48 2010

#include "DBAdmin.h"

using namespace std;

BEGIN_EVENT_TABLE(DBAdmin, wxFrame)
    EVT_BUTTON(ID_SEARCH, DBAdmin::OnSearch)
    EVT_BUTTON(ID_NEW, DBAdmin::OnNew)
    EVT_BUTTON(ID_DELETE, DBAdmin::OnDelete)
    EVT_BUTTON(ID_SAVE, DBAdmin::OnSave)

    EVT_MENU(ID_FILE_EXIT, DBAdmin::OnExit)
    EVT_MENU(ID_HELP_ABOUT, DBAdmin::OnAbout)
END_EVENT_TABLE()

// begin wxGlade: ::extracode

// end wxGlade


DBAdmin::DBAdmin(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title)//, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: DBAdmin::DBAdmin
    panel_search = new wxPanel(this);
    label_1 = new wxStaticText(panel_search, wxID_ANY, wxT("Song Name"));
    text_ctrl_search = new wxTextCtrl(panel_search, wxID_ANY, wxEmptyString);
    button_search = new wxButton(panel_search, ID_SEARCH, wxT("Search"));
    button_new = new wxButton(panel_search, ID_NEW, wxT("New Song"));
    button_delete = new wxButton(panel_search, ID_DELETE, wxT("Delete"));
    button_save = new wxButton(panel_search, ID_SAVE, wxT("Save"));
    button_save->Enable(false);
    button_delete->Enable(false);

    panel_detail = new wxPanel(this);
    label_SongName = new wxStaticText(panel_detail, wxID_ANY, wxT("Song Name"));
    text_SongName = new wxTextCtrl(panel_detail, wxID_ANY, wxEmptyString);
    label_Singer = new wxStaticText(panel_detail, wxID_ANY, wxT("Singer"));
    text_Singer = new wxTextCtrl(panel_detail, wxID_ANY, wxEmptyString);
    label_Country = new wxStaticText(panel_detail, wxID_ANY, wxT("Country"));
    text_Country = new wxTextCtrl(panel_detail, wxID_ANY);
    label_Sex = new wxStaticText(panel_detail, wxID_ANY, wxT("Gender"));
    
    wxArrayString gender; gender.Add("Male"); gender.Add("Female");
    combo_box_Sex = new wxComboBox(panel_detail, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, gender, wxCB_DROPDOWN);
    label_Band = new wxStaticText(panel_detail, wxID_ANY, wxT("Band"));
    text_ctrl_Band = new wxTextCtrl(panel_detail, wxID_ANY, wxEmptyString);
    label_Language = new wxStaticText(panel_detail, wxID_ANY, wxT("Language"));
    
    wxArrayString language; language.Add("Chinese"); language.Add("English");
    combo_box_Language = new wxComboBox(panel_detail, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, language, wxCB_DROPDOWN);

    status_bar = new wxStatusBar(this);
    InitMenus();

    set_properties();
    do_layout();
    // end wxGlade

    if(!DBConnect("KTVAdmin", "admin", "localhost", "ktv"))
        wxMessageBox("Cannot connect to the database!", "Error");
    m_state = NONE;
}

void DBAdmin::InitMenus()
{
    wxMenu* menu_file = new wxMenu;
    menu_file->Append(ID_FILE_EXIT, "Exit");

    wxMenu* menu_help = new wxMenu;
    menu_help->Append(ID_HELP_ABOUT, "About");

    wxMenuBar* menu_bar = new wxMenuBar();
    menu_bar->Append(menu_file, "File");
    menu_bar->Append(menu_help, "Help");

    SetMenuBar(menu_bar);
    SetStatusBar(status_bar);
}


void DBAdmin::set_properties()
{
    // begin wxGlade: DBAdmin::set_properties
    SetTitle(wxT("VOD System Administion"));
    // end wxGlade

    status_bar->SetFieldsCount();
    status_bar->SetStatusText("Ready...");
}


void DBAdmin::do_layout()
{
    // begin wxGlade: DBAdmin::do_layout
    wxBoxSizer* sizer_main = new wxBoxSizer(wxVERTICAL);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(6, 2, 0, 0);
    wxBoxSizer* sizer_search = new wxBoxSizer(wxHORIZONTAL);

    sizer_search->Add(label_1, 0, 0, 0);
    sizer_search->Add(text_ctrl_search, 0, 0, 0);
    sizer_search->Add(button_search, 0, 0, 0);
    sizer_search->Add(button_new, 0, 0, 0);
    sizer_search->Add(button_delete, 0, 0, 0);
    sizer_search->Add(button_save, 0, 0, 0);

    grid_sizer_1->Add(label_SongName, 0, 0, 0);
    grid_sizer_1->Add(text_SongName, 0, 0, 0);
    grid_sizer_1->Add(label_Singer, 0, 0, 0);
    grid_sizer_1->Add(text_Singer, 0, 0, 0);
    grid_sizer_1->Add(label_Country, 0, 0, 0);
    grid_sizer_1->Add(text_Country, 0, 0, 0);
    grid_sizer_1->Add(label_Sex, 0, 0, 0);
    grid_sizer_1->Add(combo_box_Sex, 0, 0, 0);
    grid_sizer_1->Add(label_Band, 0, 0, 0);
    grid_sizer_1->Add(text_ctrl_Band, 0, 0, 0);
    grid_sizer_1->Add(label_Language, 0, 0, 0);
    grid_sizer_1->Add(combo_box_Language, 0, 0, 0);
    sizer_main->Add(panel_search, 0, wxEXPAND, 0);
    sizer_main->Add(panel_detail, 5, wxEXPAND, 0);

    panel_search->SetSizer(sizer_search);
    panel_detail->SetSizer(grid_sizer_1);

    SetSizer(sizer_main);
    sizer_main->Fit(this);
    Layout();
    // end wxGlade
}

void DBAdmin::OnSearch(wxCommandEvent& event)
{
    Songs result;
    if( m_state == MODIFIED || m_state == NEW )
    {
        if( wxMessageBox("Current song modified, are you sure to discard?", "Confirm", wxYES_NO)!=wxYES )
            return;
    }

    status_bar->SetStatusText("Searching...");

    string cmd = "SELECT * from songs where name = '" + text_ctrl_search->GetValue() + "'";
    SearchSong(cmd, result);

    if( result.empty() &&
        wxMessageBox("No such song found, are you willing to take a look at a random song?", 
                     "info", wxYES_NO) == wxYES)
    {
        cmd = "SELECT * from songs";
        SearchSong(cmd, result);
    }

    if( !result.empty() )
    {
        text_SongName->SetValue(result[0].name);
        text_Country->SetValue(result[0].country);
        combo_box_Sex->SetValue(result[0].gender);
        text_ctrl_Band->SetValue(result[0].band);
        combo_box_Language->SetValue(result[0].language);
        button_save->Enable(false);
        status_bar->SetStatusText("Search succeed");
        
        m_state = NOT_MODIFIED;
        button_delete->Enable(true);
        button_save->Enable(false);
    }
    else
    {
        status_bar->SetStatusText("Search failed");
        m_state = NONE;
    }
}

void DBAdmin::OnNew(wxCommandEvent& event)
{
    m_state = NEW;
    text_SongName->SetValue("");
    text_Singer->SetValue("");
    text_Country->SetValue("");
    combo_box_Sex->SetValue("Male");
    text_ctrl_Band->SetValue("");
    combo_box_Language->SetValue("Chinese");

    button_save->Enable(true);
    button_delete->Enable(false);
    status_bar->SetStatusText("New Song");
}

void DBAdmin::OnDelete(wxCommandEvent& event)
{
    wxString stmt;

    if(text_SongName->GetValue().empty())
        return;
    if(wxMessageBox("Are you sure to delete", "Confirm", wxYES_NO) != wxYES)
        return;

    stmt.Printf("DELETE from songs WHERE name = '%s'", text_SongName->GetValue() );
    if( DBExecute(string(stmt)) )
    {
        wxMessageBox("Delete succeed", "Info");
        text_SongName->SetValue("");
        text_Singer->SetValue("");
        text_Country->SetValue("");
        combo_box_Sex->SetValue("Male");
        text_ctrl_Band->SetValue("");
        combo_box_Language->SetValue("Chinese");
        button_save->Enable(false);
        button_new->Enable();
        button_delete->Enable(false);
    }
}

void DBAdmin::OnSave(wxCommandEvent& event)
{
    if(text_SongName->GetValue().empty() ||
        text_Singer->GetValue().empty() )
    {
        wxMessageBox("Please fill the form before submitting", "Info");
        return;
    }
    button_delete->Enable();
    status_bar->SetStatusText("SaveÖÐ...");

    wxString stmt;
    stmt.Printf("INSERT INTO songs (name, singer, country, gender, band, language) "
        "VALUES ('%s', '%s', '%s', '%s', '%s', '%s') ",
        text_SongName->GetValue(), 
        text_Singer->GetValue(),
        text_Country->GetValue(),
        combo_box_Sex->GetValue(),
        text_ctrl_Band->GetValue(),
        combo_box_Language->GetValue());

    if( DBExecute(string(stmt)) )
    {
        m_state = NOT_MODIFIED;
        wxMessageBox("Update Succeed", "Info");
        button_save->Enable(false);
        status_bar->SetStatusText("Saved");
    }
    status_bar->SetStatusText("Save failed");
}

void DBAdmin::OnAbout(wxCommandEvent& WXUNUSED(event))
{
    wxMessageBox(wxString::Format(
                    _T("VOD System Administration\n")
                    _T("Based on wxWidget %s£¬MySql 5.1\n")
                    _T("Now running under %s."),
                    wxVERSION_STRING,
                    wxGetOsDescription().c_str()
                 ),
                 _T("About this program"),
                 wxOK | wxICON_INFORMATION,
                 this);
}

void DBAdmin::OnExit(wxCommandEvent& WXUNUSED(event))
{
    Close(true);
}