// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Apr 30 19:20:48 2010

#include <wx/wx.h>
#include "DBAdmin.h"

class MyApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    wxInitAllImageHandlers();
    DBAdmin* frame_main = new DBAdmin(NULL, wxID_ANY, "数据库管理程序");
    SetTopWindow(frame_main);
    frame_main->Show();
    return true;
}
